Jenil dhokiya 
23SOEIT11003

In [261]:
print("hello world")

hello world

Tutorial:-Explore Numpy Library to analyze data
The python package numpy , which stands for "numerical python"

In [262]:
import numpy as np
print (np.__version__)

2.3.5

In [263]:
#list
a = [1,2,3,4,4]
print(a)

[1, 2, 3, 4, 4]

Q1.Find difference between python list and numpy array.

In [264]:

x= np.array(a)
x

array([1, 2, 3, 4, 4])

#create a 1D array with 5 element

In [265]:
#create a 1D array with 5 element
y = np.array([12,23,34,45,56])
y

array([12, 23, 34, 45, 56])

In [266]:
j = np.random.randint(0,5,11)
j

array([0, 4, 2, 1, 3, 3, 1, 1, 4, 3, 1], dtype=int32)

In [267]:
#2D array
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,13]])
print(a)
a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 13]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [268]:
m = np.random.rand(2,2)
m
n = np.random.randint(0,5,(3,3))
n

array([[1, 1, 0],
       [2, 0, 1],
       [1, 2, 0]], dtype=int32)

In [269]:
#3d array
s = np.array([[1,2,3],[4,5,6],[5,6,7],[9,9,9]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7],
       [9, 9, 9]])

In [270]:
k=np.zeros((3,4),dtype=int)
k

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [271]:
t=np.ones((5,5),dtype=int)
t

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [272]:
w=np.full((5,5),4)
w

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [273]:
e=np.eye(4,5,dtype=int)
e

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [274]:
e=5*np.eye(4,5,dtype=int)
e

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0]])

In [275]:
print("shape of e",e.shape)

a.ndim

shape of e (4, 5)

2

In [276]:
a.size

12

In [277]:
a.dtype

dtype('int64')

In [278]:
x=np.array([12,23,43,45,56,67])
x.min()

np.int64(12)

In [279]:
x.max()

np.int64(67)

In [280]:
x.argmin()

np.int64(0)

In [281]:
x.argmax()

np.int64(5)

In [282]:
x.mean()

np.float64(41.0)

In [283]:
print(x.mean())

41.0

In [284]:
r=np.array([[1,2,3],[1,2,3]])
y=np.array([[2,3,4],[2,3,4]])
print(r+y)
np.add(r,y)

[[3 5 7]
 [3 5 7]]

array([[3, 5, 7],
       [3, 5, 7]])

In [285]:
r=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
y=np.array([[2,3,4],[2,3,4],[1,2,3],[1,2,3]])
print(r-y)
np.subtract(r,y)

[[-1 -1 -1]
 [-1 -1 -1]
 [ 0  0  0]
 [ 0  0  0]]

array([[-1, -1, -1],
       [-1, -1, -1],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [286]:
r=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
y=np.array([[2,3,4],[2,3,4],[1,2,3],[1,2,3]])
print(r*y)
np.multiply(r,y)

[[ 2  6 12]
 [ 2  6 12]
 [ 1  4  9]
 [ 1  4  9]]

array([[ 2,  6, 12],
       [ 2,  6, 12],
       [ 1,  4,  9],
       [ 1,  4,  9]])

In [287]:
r=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
y=np.array([[2,3,4],[2,3,4],[1,2,3],[1,2,3]])
print(r/y)
np.divide(r,y)

[[0.5        0.66666667 0.75      ]
 [0.5        0.66666667 0.75      ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]

array([[0.5       , 0.66666667, 0.75      ],
       [0.5       , 0.66666667, 0.75      ],
       [1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])

Q2. Y numpy is faster than list  
Q3. where numpy manly used

Indexing is used to access element in lists, arrays, strings, or other data structures.  
Python uses zero-based indexing (0 is the first element).  
Negative indexing allows access from the end of the structure.  
In 2D arrays, indexing requires row and column indices.  
Indexing is the process of accessing a single element from a sequence using its position or index.

Question 22  
Print index 2 and -2 value for 1D array. (indexing).

In [288]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [289]:
print(a[2],a[-2])

3 8

Question 23  
Perform indexing operations with 2D array.

In [290]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [291]:
print(a[1][2])

6

Question 24  
Print value of index 2 to 5 (slicing)

In [292]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[2:6]

array([3, 4, 5, 6])

Question 25  
Print from index 0 to 5 values

In [293]:
a[0:6]

array([1, 2, 3, 4, 5, 6])

Question 26  
Print from index 5 to all

In [294]:
a[5:]

array([6, 7, 8, 9])

Question 27  
Reassign value for particular index.

In [295]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7,  8,  9])

Question 28  
Reassign value 100 to all elements.

In [296]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[:] = 100
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

Question 29  
Extract elements from index 1 to 7 with a step of 2.

In [297]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[1:8:2]

array([2, 4, 6, 8])

Question 30  
Print Reverse the array.

In [298]:
a = np.array([1,2,3,4,5,6,7,8,9])
a = np.flip(a)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [299]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.  
Description: Use Pandas library for data analysis and manipulation.  

Dataset: Sample CSV file  

Task: Load the dataset, perform data cleaning, manipulation (like sorting, filtering), and exploratory data analysis.

Pandas is an open-source library for real world data analysis in python.  
It is built on top of MumPy.  
The basic data structures of Pandas are Series and Dataframe.  
1. Series: Series is a one dimensional labeled array.  
2. DataFrame: A DataFrame is pandas is a two-dimensional, tabural data structure similar to a spreadsheet or SQL table.    

It consists of rows and columns.

Question 1  
Import numpy and pandas library.

In [300]:
import numpy as np
import pandas as pd

Question 2  
Define series with 3 elements.

In [301]:
s1 = pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

Question 3  
Define a series with a custom index.

In [302]:
s2 = pd.Series([1,2,3,4],["A","B","C","D"])
s2

A    1
B    2
C    3
D    4
dtype: int64

Find a difference between list, 1D numpy array, and series

Question 4  
Fetch Series value and index.

Question 5  
Create DataFrame from list of Dict.

In [303]:
data = [{'Name': 'Subodh','Marks': 28},{'Name':'Ram','Marks':27},{'Name':'Abdul'},{'Name':'John','Marks':28}]
f1 = pd.DataFrame(data)
f1

     Name  Marks
0  Subodh   28.0
1     Ram   27.0
2   Abdul    NaN
3    John   28.0

In [304]:
f1.isna().sum()

Name     0
Marks    1
dtype: int64

Question 6  
Create sample excel file in your computer with columns “name”, “Branch” and “Division”. Add atleast 5 records in excel file.  Read the excel file in .ipynb.

In [305]:
student_data = pd.read_excel("Book1.xlsx")
student_data

      name Branch Division
0  Durgesh     IT        A
1    Jenil     IT        A
2      Jay     CE        A
3   Kishan     CE        A
4     Ansh     IT        A

In [306]:
iris_data = pd.read_csv("datasets/Iris.csv")
iris_data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [307]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [308]:
iris_data.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [309]:
iris_data["Species"].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [310]:
iris_data.index

RangeIndex(start=0, stop=150, step=1)

In [311]:
iris_data.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [312]:
iris_data = iris_data.rename(columns={"Sepal.Length":"Sepal_Length","Sepal.Width":"Sepal_Width","Petal.Length":"Petal_Length","Petal.Width":"Petal_Width"})
iris_data.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'],
      dtype='object')

In [313]:
iris_data

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [314]:
iris_data["Species"].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [315]:
iris_data["Species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [316]:
iris_data["Species"].replace("setosa","Setosa",inplace=True)

C:\Users\JEN1L\AppData\Local\Temp\ipykernel_12328\3072939811.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris_data["Species"].replace("setosa","Setosa",inplace=True)

In [317]:
iris_data["Species"].unique()

array(['Setosa', 'versicolor', 'virginica'], dtype=object)

In [318]:
iris_data["Species"].replace("versicolor","Versicolor",inplace=True)
iris_data["Species"].replace("virginica","Virginica",inplace=True)

C:\Users\JEN1L\AppData\Local\Temp\ipykernel_12328\864908691.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris_data["Species"].replace("versicolor","Versicolor",inplace=True)
C:\Users\JEN1L\AppData\Local\Temp\ipykernel_12328\864908691.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris_data["Species"].replace("virginica","Virginica",inplace=True)

In [319]:
iris_data["Species"].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [320]:
iris_data.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [321]:
iris_data[["Petal_Length","Petal_Width"]]

     Petal_Length  Petal_Width
0             1.4          0.2
1             1.4          0.2
2             1.3          0.2
3             1.5          0.2
4             1.4          0.2
..            ...          ...
145           5.2          2.3
146           5.0          1.9
147           5.2          2.0
148           5.4          2.3
149           5.1          1.8

[150 rows x 2 columns]

In [322]:
def yes_no(Sepal_Length):
  return 'YES' if Sepal_Length >= 5 else "NO"

iris_data["Result"] = iris_data["Sepal_Length"].apply(yes_no)
iris_data["Result"].value_counts()

Result
YES    128
NO      22
Name: count, dtype: int64

In [323]:
iris_data.drop('Result',axis=1,inplace=True)
iris_data

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [324]:
n = int(input())
product=1
for i in range(1,n+1):
  product*=i
output = 0
for i in str(product):
  output+=int(i)
print(output)

3

In [325]:
iris_data[(iris_data["Petal_Length"]>5)& (iris_data["Species"]=="Virginica")].duplicated().sum()

np.int64(1)

In [326]:
iris_data.duplicated().sum()

np.int64(1)

Read dataset student_info.csv  
Find info  
Find columns  
Find the missing value

In [327]:
student = pd.read_csv("datasets/student_info.csv")
student

     study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]

In [328]:
student.describe()

       study_hours  student_marks
count   195.000000      200.00000
mean      6.995949       77.93375
std       1.253060        4.92570
min       5.010000       68.57000
25%       5.775000       73.38500
50%       7.120000       77.71000
75%       8.085000       82.32000
max       8.990000       86.99000

In [329]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   study_hours    195 non-null    float64
 1   student_marks  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB

In [330]:
student.columns

Index(['study_hours', 'student_marks'], dtype='object')

In [331]:
student.isna().sum()

study_hours      5
student_marks    0
dtype: int64

In [332]:
student['study_hours'] = student['study_hours'].fillna(student['study_hours'].mean())
student.isna().sum()

study_hours      0
student_marks    0
dtype: int64

In [333]:
student = student.rename(columns={"student_marks":"Student_Marks"})
student["Student_Marks"]

0      78.50
1      76.74
2      78.68
3      71.82
4      84.19
       ...
195    81.67
196    84.68
197    86.75
198    78.05
199    83.50
Name: Student_Marks, Length: 200, dtype: float64

In [334]:
student

     study_hours  Student_Marks
0       6.830000          78.50
1       6.560000          76.74
2       6.995949          78.68
3       5.670000          71.82
4       8.670000          84.19
..           ...            ...
195     7.530000          81.67
196     8.560000          84.68
197     8.940000          86.75
198     6.600000          78.05
199     8.350000          83.50

[200 rows x 2 columns]

In [335]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
adult = fetch_ucirepo(id=2)

# data (as pandas dataframes)
X = adult.data.features
y = adult.data.targets

# metadata
print(adult.metadata)

# variable information
print(adult.variables)

IncompleteRead: IncompleteRead(270261 bytes read)

In [ ]:
X.info()

In [ ]:
X.isna().sum()

In [ ]:
X.head()

In [ ]:
X.tail()

In [ ]:
X.nunique()

In [ ]:
X['workclass'].unique()

In [ ]:
X["workclass"].value_counts()

In [ ]:
X['workclass'].mode()

In [ ]:
X['workclass']=X['workclass'].fillna(X['workclass'].mode()[0])
X['workclass'].isna().sum()

In [ ]:
X['workclass'].unique()

In [ ]:
X['workclass'].isna().sum()

In [ ]:
X['occupation'].isna().sum()

In [ ]:
X['occupation'] = X['occupation'].fillna(X['occupation'].mode()[0])

In [ ]:
X['occupation'].isna().sum()

In [ ]:
X.isna().sum()

In [ ]:
X.dropna(how='any',inplace=True)

In [ ]:
X.isna().sum()

# **Tutorial 3: Visualize Data Using Matplotlib and Seaborn Library**

In [ ]:
pip install seaborn

In [ ]:
import seaborn as sns

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
clean_dataset = pd.read_csv("datasets/Clean_Dataset.csv")

In [ ]:
clean_dataset

In [ ]:
clean_dataset.info()

In [ ]:
clean_dataset.isna().sum()

In [ ]:
clean_dataset.head()

In [ ]:
clean_dataset.columns

In [ ]:
clean_dataset=clean_dataset.rename(columns={"Unnamed: 0":"id"})

In [ ]:
clean_dataset

In [ ]:
clean_dataset.tail()

# **1. Count plot (used for categorical data)**  

Count plot are used when you have categorical variables, and you want to visualize the distribution of these categories.

In [ ]:
# Count plot
clean_dataset['source_city'].unique()

In [ ]:
clean_dataset.nunique()

In [ ]:
sns.countplot(x='source_city',data=clean_dataset)

In [ ]:
sns.countplot(x='class',data=clean_dataset)

In [ ]:
sns.countplot(y='source_city',data=clean_dataset)

# 2. **Pie Chart (Categorical data)**   
A pie chart represent the parts of a whole entity

In [ ]:
clean_dataset['class'].value_counts().plot(kind='pie',autopct='%.2f')

In [ ]:
clean_dataset['class'].value_counts().plot(kind='line')

In [ ]:
clean_dataset['source_city'].value_counts().plot(kind='pie',autopct="%.2f")

# 3. **Donut plots (used for categorical data)**  
Donut plots are used to show the proportion of each category

In [ ]:
plt.pie(clean_dataset['source_city'].value_counts(),labels=clean_dataset['source_city'].unique(),autopct="%.2f",wedgeprops=dict(width=0.2))

# 4. **Histogram (used for numerical data) (Countinuos Variables)**  
Histogram are used when you have a continous varibles, and you want to viualize its distribution.

In [ ]:
plt.hist(clean_dataset[['price']])

In [ ]:
clean_dataset.tail()

# 5. **Ditribution plot (Continuos Data to show distribution)**

In [ ]:
sns.histplot(clean_dataset['duration'])

In [ ]:
sns.displot(clean_dataset['duration'])

# Implement box plot, scatter plot, line plot with suitable data

In [ ]:
clean_dataset['price'].plot(kind='box')